# Configuration file

# Database configuration
database:
  host: "127.0.0.1"
  port: 3306
  user: root
  password: ""
  database: "child_in_time"

# Version information
version:
  name: "0.1"
  code: 1