# Configuration file

# Database configuration
database:
  hostname: "127.0.0.1"
  database: "child_in_time"
  username: root
  password: ""
  port: 3306

# Version information
version:
  name: "0.1"
  code: 1